apiVersion: v1
kind: Service
metadata:
  name: hello-python-service
spec:
  selector:
    app: hello-python
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 5000          # internal service port for app
      targetPort: 5000    # container port
      nodePort: 30007     # external access port
    - name: metrics
      protocol: TCP
      port: 8000          # internal service port for metrics
      targetPort: 8000    # container port metrics
      nodePort: 30008     # external access for metrics if needed
