apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;

        # Serve HTML
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        # Stub status for Prometheus
        location /stub_status {
            stub_status;
            access_log off;
            allow 127.0.0.1;        # localhost
            allow 10.244.0.0/16;    # Minikube pod network
            deny all;
        }
    }
