apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  stub_status.conf: |
    server {
      listen 80;

      location / {
        root /usr/share/nginx/html;
        index index.html;
      }

      location /stub_status {
        stub_status;
        allow all;
      }
    }
