apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: kube-system
spec:
  selector:
    k8s-app: node-exporter
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 9100
